require 'faker'

puts "🌱 Seeding spices..."

# Seed your database here
d1 = Date_d.create(date: "12/1/2021")
d2 = Date_d.create(date: "12/2/2021")
d3 = Date_d.create(date: "12/3/2021")
d4 = Date_d.create(date: "12/4/2021")
d5 = Date_d.create(date: "12/5/2021")
d6 = Date_d.create(date: "12/6/2021")
d7 = Date_d.create(date: "12/7/2021")
d8 = Date_d.create(date: "12/8/2021")
d9 = Date_d.create(date: "12/9/2021")
d10 = Date_d.create(date: "12/10/2021")
d11 = Date_d.create(date: "12/11/2021")
d12 = Date_d.create(date: "12/12/2021")
d13 = Date_d.create(date: "12/13/2021")
d14 = Date_d.create(date: "12/14/2021")
d15 = Date_d.create(date: "12/15/2021")
d16 = Date_d.create(date: "12/16/2021")
d17 = Date_d.create(date: "12/17/2021")
d18 = Date_d.create(date: "12/18/2021")
d19 = Date_d.create(date: "12/19/2021")
d20 = Date_d.create(date: "12/20/2021")
d21 = Date_d.create(date: "12/21/2021")
d22 = Date_d.create(date: "12/22/2021")
d23 = Date_d.create(date: "12/23/2021")
d24 = Date_d.create(date: "12/24/2021")
d25 = Date_d.create(date: "12/25/2021")
d26 = Date_d.create(date: "12/26/2021")
d27 = Date_d.create(date: "12/27/2021")
d28 = Date_d.create(date: "12/28/2021")
d29 = Date_d.create(date: "12/29/2021")
d30 = Date_d.create(date: "12/30/2021")
d31 = Date_d.create(date: "12/31/2021")
d32 = Date_d.create(date: "1/1/2022")


e3= Event.create(name: "Rosa Parks Day", country: "US", location: "United States - Oregon", holiday_type: "Local observance", date_d_id: d1.id)
e4=Event.create(name: "World AIDS Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d1.id)
e5=Event.create(name: "Rosa Parks Day", country: "US", location: "United States - Ohio", holiday_type: "Local observance", date_d_id: d1.id)
e6=Event.create(name: "International Day for the Abolition of Slavery", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d2.id)
e7=Event.create(name: "International Day of Persons with Disabilities", country: "US", location: "United States", holiday_type: "UN observance",date_d_id: d3.id)
e8=Event.create(name: "World Soil Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d5.id)
e9=Event.create(name: "International Volunteer Day for Economic and Social Development", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d5.id)
e10=Event.create(name: "Last Day of Chanukah", country: "US", location: "United States", holiday_type: "Hebrew", date_d_id: d6.id)
e11=Event.create(name: "St Nicholas Day", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d6.id)
e12=Event.create(name: "Pearl Harbor Remembrance Day", country: "US", location: "United States" , holiday_type: "Observance", date_d_id: d7.id)
e13=Event.create(name: "International Civil Aviation Day", country: "US", location: "United States", holiday_type: "UN observance" , date_d_id: d7.id)
e14=Event.create(name: "Feast of the Immaculate Conception", country: "US", location: "United States", holiday_type: "Christian", date_d_id: d8.id)
e15=Event.create(name: "International Anti-Corruption Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d9.id)
e16=Event.create(name: "World Genocide Commemoration Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d9.id)
e17=Event.create(name: "Human Rights Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d10.id)
e18=Event.create(name: "International Mountain Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d11.id)
e19=Event.create(name: "Feast of Our Lady of Guadalupe", country: "US", location: "United States", holiday_type: "Christian", date_d_id: d12.id)
e20=Event.create(name: "National Guard Birthday", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d13.id)
e21=Event.create(name: "Bill of Rights Day", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d15.id)
e22=Event.create(name: "Wright Brothers Day", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d17.id)
e23=Event.create(name: "Pan American Aviation Day", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d17.id)
e24=Event.create(name: "International Migrants Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d18.id)
e25=Event.create(name: "Arabic Language Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d18.id)
e26=Event.create(name: "International Human Solidarity Day", country: "US", location: "United States", holiday_type: "UN observance", date_d_id: d20.id)
e27=Event.create(name: "December Solstice", country: "US",location: "United States", holiday_type: "Seasonal", date_d_id: d21.id)
e28=Event.create(name: "Christmas Eve", country: "US", location: "United States - Michigan, Kansas, North Carolina, North Dakota, Oklahoma, South Carolina, Texas, Wisconsin, Virginia, Kentucky", holiday_type: "Local holiday", date_d_id: d24.id)
e29=Event.create(name: "Christmas Day", country: "US", location: "United States", holiday_type: "National", date_d_id: d24.id)
e30=Event.create(name: "Christmas Eve", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d24.id)
e31=Event.create(name: "Christmas Day", country: "US", location: "United States", holiday_type: "National", date_d_id: d25.id)
e32=Event.create(name: "Day After Christmas Day", country: "US", location: "United States - Texas, Kansas, North Carolina, South Carolina", holiday_type: "Local holiday", date_d_id: d26.id)
e33=Event.create(name: "Kwanzaa (first day)", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d26.id)
e34=Event.create(name: "New Year's Eve", country: "US", location: "United States - Wisconsin, Louisiana, Michigan", holiday_type: "Local holiday", date_d_id: d31.id)
e35=Event.create(name: "New Year's Eve", country: "US", location: "United States", holiday_type: "Observance", date_d_id: d31.id)
e36=Event.create(name: "New Year's Day", country: "US", location: "United States", holiday_type: "National", date_d_id: d32.id)

puts "✅ Done seeding!"
